import type { Metadata } from 'next'
import './globals.css'
import ConditionalHeader from '@/components/ConditionalHeader'
import ConditionalFooter from '@/components/ConditionalFooter'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'Event Scheduler',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`h-[100vh] flex flex-col`}>
        <Toaster position='top-right' />
        <ConditionalHeader />
        <div className='flex-1'>{children}</div>
        <ConditionalFooter />
      </body>
    </html>
  )
}
